/*
 * ZIQNI Admin API
 *
 * Ziqni Application Services are used to manage and configure spaces.
 *
 * The version of the OpenAPI document: 3.0.9
 * Contact: support@ziqni.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Ziqni.Api;
using Ziqni.Model;
using Ziqni.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Ziqni.Test
{
    /// <summary>
    ///  Class for testing Bracket
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BracketTests
    {
        // TODO uncomment below to declare an instance variable for Bracket
        //private Bracket instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Bracket
            //instance = new Bracket();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Bracket
        /// </summary>
        [Test]
        public void BracketInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" Bracket
            //Assert.IsInstanceOf(typeof(Bracket), instance);
        }


        /// <summary>
        /// Test the property 'Rounds'
        /// </summary>
        [Test]
        public void RoundsTest()
        {
            // TODO unit test for the property 'Rounds'
        }
        /// <summary>
        /// Test the property 'Contests'
        /// </summary>
        [Test]
        public void ContestsTest()
        {
            // TODO unit test for the property 'Contests'
        }

    }

}
