/*
 * ZIQNI Admin API
 *
 * Ziqni Application Services are used to manage and configure spaces.
 *
 * The version of the OpenAPI document: 3.0.9
 * Contact: support@ziqni.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Ziqni.Api;
using Ziqni.Model;
using Ziqni.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Ziqni.Test
{
    /// <summary>
    ///  Class for testing ClaimAwardRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ClaimAwardRequestTests
    {
        // TODO uncomment below to declare an instance variable for ClaimAwardRequest
        //private ClaimAwardRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ClaimAwardRequest
            //instance = new ClaimAwardRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ClaimAwardRequest
        /// </summary>
        [Test]
        public void ClaimAwardRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ClaimAwardRequest
            //Assert.IsInstanceOf(typeof(ClaimAwardRequest), instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Constraints'
        /// </summary>
        [Test]
        public void ConstraintsTest()
        {
            // TODO unit test for the property 'Constraints'
        }

    }

}
