/*
 * ZIQNI Admin API
 *
 * Ziqni Application Services are used to manage and configure spaces.
 *
 * The version of the OpenAPI document: 3.0.9
 * Contact: support@ziqni.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Ziqni.Api;
using Ziqni.Model;
using Ziqni.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Ziqni.Test
{
    /// <summary>
    ///  Class for testing CreateFileObjectRequestAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateFileObjectRequestAllOfTests
    {
        // TODO uncomment below to declare an instance variable for CreateFileObjectRequestAllOf
        //private CreateFileObjectRequestAllOf instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CreateFileObjectRequestAllOf
            //instance = new CreateFileObjectRequestAllOf();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CreateFileObjectRequestAllOf
        /// </summary>
        [Test]
        public void CreateFileObjectRequestAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" CreateFileObjectRequestAllOf
            //Assert.IsInstanceOf(typeof(CreateFileObjectRequestAllOf), instance);
        }


        /// <summary>
        /// Test the property 'RepositoryId'
        /// </summary>
        [Test]
        public void RepositoryIdTest()
        {
            // TODO unit test for the property 'RepositoryId'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'MimeType'
        /// </summary>
        [Test]
        public void MimeTypeTest()
        {
            // TODO unit test for the property 'MimeType'
        }
        /// <summary>
        /// Test the property 'ParentFolderPath'
        /// </summary>
        [Test]
        public void ParentFolderPathTest()
        {
            // TODO unit test for the property 'ParentFolderPath'
        }
        /// <summary>
        /// Test the property 'Constraints'
        /// </summary>
        [Test]
        public void ConstraintsTest()
        {
            // TODO unit test for the property 'Constraints'
        }

    }

}
