/*
 * ZIQNI Admin API
 *
 * Ziqni Application Services are used to manage and configure spaces.
 *
 * The version of the OpenAPI document: 3.0.9
 * Contact: support@ziqni.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Ziqni.Api;
using Ziqni.Model;
using Ziqni.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Ziqni.Test
{
    /// <summary>
    ///  Class for testing EventRefType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EventRefTypeTests
    {
        // TODO uncomment below to declare an instance variable for EventRefType
        //private EventRefType instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EventRefType
            //instance = new EventRefType();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EventRefType
        /// </summary>
        [Test]
        public void EventRefTypeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" EventRefType
            //Assert.IsInstanceOf(typeof(EventRefType), instance);
        }



    }

}
