/*
 * ZIQNI Admin API
 *
 * Ziqni Application Services are used to manage and configure spaces.
 *
 * The version of the OpenAPI document: 3.0.9
 * Contact: support@ziqni.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Ziqni.Api;
using Ziqni.Model;
using Ziqni.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Ziqni.Test
{
    /// <summary>
    ///  Class for testing RuleArgument
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RuleArgumentTests
    {
        // TODO uncomment below to declare an instance variable for RuleArgument
        //private RuleArgument instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RuleArgument
            //instance = new RuleArgument();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RuleArgument
        /// </summary>
        [Test]
        public void RuleArgumentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" RuleArgument
            //Assert.IsInstanceOf(typeof(RuleArgument), instance);
        }


        /// <summary>
        /// Test the property 'Argument'
        /// </summary>
        [Test]
        public void ArgumentTest()
        {
            // TODO unit test for the property 'Argument'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Test]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Order'
        /// </summary>
        [Test]
        public void OrderTest()
        {
            // TODO unit test for the property 'Order'
        }

    }

}
