/*
 * ZIQNI Admin API
 *
 * Ziqni Application Services are used to manage and configure spaces.
 *
 * The version of the OpenAPI document: 3.0.9
 * Contact: support@ziqni.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Ziqni.Api;
using Ziqni.Model;
using Ziqni.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Ziqni.Test
{
    /// <summary>
    ///  Class for testing Scheduling
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SchedulingTests
    {
        // TODO uncomment below to declare an instance variable for Scheduling
        //private Scheduling instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Scheduling
            //instance = new Scheduling();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Scheduling
        /// </summary>
        [Test]
        public void SchedulingInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" Scheduling
            //Assert.IsInstanceOf(typeof(Scheduling), instance);
        }


        /// <summary>
        /// Test the property 'ScheduleType'
        /// </summary>
        [Test]
        public void ScheduleTypeTest()
        {
            // TODO unit test for the property 'ScheduleType'
        }
        /// <summary>
        /// Test the property 'ScheduleOccurrencesLimit'
        /// </summary>
        [Test]
        public void ScheduleOccurrencesLimitTest()
        {
            // TODO unit test for the property 'ScheduleOccurrencesLimit'
        }
        /// <summary>
        /// Test the property 'Every'
        /// </summary>
        [Test]
        public void EveryTest()
        {
            // TODO unit test for the property 'Every'
        }
        /// <summary>
        /// Test the property 'StartDate'
        /// </summary>
        [Test]
        public void StartDateTest()
        {
            // TODO unit test for the property 'StartDate'
        }
        /// <summary>
        /// Test the property 'EndDate'
        /// </summary>
        [Test]
        public void EndDateTest()
        {
            // TODO unit test for the property 'EndDate'
        }
        /// <summary>
        /// Test the property 'Constraints'
        /// </summary>
        [Test]
        public void ConstraintsTest()
        {
            // TODO unit test for the property 'Constraints'
        }

    }

}
