/*
 * ZIQNI Admin API
 *
 * Ziqni Application Services are used to manage and configure spaces.
 *
 * The version of the OpenAPI document: 3.0.9
 * Contact: support@ziqni.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Ziqni.Api;
using Ziqni.Model;
using Ziqni.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Ziqni.Test
{
    /// <summary>
    ///  Class for testing TournamentStrategies
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TournamentStrategiesTests
    {
        // TODO uncomment below to declare an instance variable for TournamentStrategies
        //private TournamentStrategies instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TournamentStrategies
            //instance = new TournamentStrategies();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TournamentStrategies
        /// </summary>
        [Test]
        public void TournamentStrategiesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" TournamentStrategies
            //Assert.IsInstanceOf(typeof(TournamentStrategies), instance);
        }


        /// <summary>
        /// Test the property 'StrategyType'
        /// </summary>
        [Test]
        public void StrategyTypeTest()
        {
            // TODO unit test for the property 'StrategyType'
        }
        /// <summary>
        /// Test the property 'RankingStrategy'
        /// </summary>
        [Test]
        public void RankingStrategyTest()
        {
            // TODO unit test for the property 'RankingStrategy'
        }
        /// <summary>
        /// Test the property 'ScoringStrategy'
        /// </summary>
        [Test]
        public void ScoringStrategyTest()
        {
            // TODO unit test for the property 'ScoringStrategy'
        }

    }

}
