/*
 * ZIQNI Admin API
 *
 * Ziqni Application Services are used to manage and configure spaces.
 *
 * The version of the OpenAPI document: 3.0.9
 * Contact: support@ziqni.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Ziqni.Api;
using Ziqni.Model;
using Ziqni.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Ziqni.Test
{
    /// <summary>
    ///  Class for testing UnitOfMeasureAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UnitOfMeasureAllOfTests
    {
        // TODO uncomment below to declare an instance variable for UnitOfMeasureAllOf
        //private UnitOfMeasureAllOf instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UnitOfMeasureAllOf
            //instance = new UnitOfMeasureAllOf();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UnitOfMeasureAllOf
        /// </summary>
        [Test]
        public void UnitOfMeasureAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" UnitOfMeasureAllOf
            //Assert.IsInstanceOf(typeof(UnitOfMeasureAllOf), instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Test]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'IsoCode'
        /// </summary>
        [Test]
        public void IsoCodeTest()
        {
            // TODO unit test for the property 'IsoCode'
        }
        /// <summary>
        /// Test the property 'Symbol'
        /// </summary>
        [Test]
        public void SymbolTest()
        {
            // TODO unit test for the property 'Symbol'
        }
        /// <summary>
        /// Test the property 'Multiplier'
        /// </summary>
        [Test]
        public void MultiplierTest()
        {
            // TODO unit test for the property 'Multiplier'
        }
        /// <summary>
        /// Test the property 'UnitOfMeasureType'
        /// </summary>
        [Test]
        public void UnitOfMeasureTypeTest()
        {
            // TODO unit test for the property 'UnitOfMeasureType'
        }

    }

}
