/*
 * ZIQNI Admin API
 *
 * Ziqni Application Services are used to manage and configure spaces.
 *
 * The version of the OpenAPI document: 3.0.9
 * Contact: support@ziqni.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Ziqni.Api;
using Ziqni.Model;
using Ziqni.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Ziqni.Test
{
    /// <summary>
    ///  Class for testing UpdateRewardRequestAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateRewardRequestAllOfTests
    {
        // TODO uncomment below to declare an instance variable for UpdateRewardRequestAllOf
        //private UpdateRewardRequestAllOf instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UpdateRewardRequestAllOf
            //instance = new UpdateRewardRequestAllOf();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UpdateRewardRequestAllOf
        /// </summary>
        [Test]
        public void UpdateRewardRequestAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" UpdateRewardRequestAllOf
            //Assert.IsInstanceOf(typeof(UpdateRewardRequestAllOf), instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'RewardRank'
        /// </summary>
        [Test]
        public void RewardRankTest()
        {
            // TODO unit test for the property 'RewardRank'
        }
        /// <summary>
        /// Test the property 'RewardValue'
        /// </summary>
        [Test]
        public void RewardValueTest()
        {
            // TODO unit test for the property 'RewardValue'
        }
        /// <summary>
        /// Test the property 'RewardTypeId'
        /// </summary>
        [Test]
        public void RewardTypeIdTest()
        {
            // TODO unit test for the property 'RewardTypeId'
        }
        /// <summary>
        /// Test the property 'Icon'
        /// </summary>
        [Test]
        public void IconTest()
        {
            // TODO unit test for the property 'Icon'
        }
        /// <summary>
        /// Test the property 'IssueLimit'
        /// </summary>
        [Test]
        public void IssueLimitTest()
        {
            // TODO unit test for the property 'IssueLimit'
        }
        /// <summary>
        /// Test the property 'Delay'
        /// </summary>
        [Test]
        public void DelayTest()
        {
            // TODO unit test for the property 'Delay'
        }
        /// <summary>
        /// Test the property 'PointInTime'
        /// </summary>
        [Test]
        public void PointInTimeTest()
        {
            // TODO unit test for the property 'PointInTime'
        }
        /// <summary>
        /// Test the property 'Period'
        /// </summary>
        [Test]
        public void PeriodTest()
        {
            // TODO unit test for the property 'Period'
        }
        /// <summary>
        /// Test the property 'AddConstraints'
        /// </summary>
        [Test]
        public void AddConstraintsTest()
        {
            // TODO unit test for the property 'AddConstraints'
        }
        /// <summary>
        /// Test the property 'RemoveConstraints'
        /// </summary>
        [Test]
        public void RemoveConstraintsTest()
        {
            // TODO unit test for the property 'RemoveConstraints'
        }

    }

}
