/**
 * ZIQNI Admin API
 * Ziqni Application Services are used to manage and configure spaces.
 *
 * The version of the OpenAPI document: 3.0.1
 * Contact: support@ziqni.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateKafkaConnectionRequestAllOf model module.
 * @module model/CreateKafkaConnectionRequestAllOf
 * @version 0.0.26
 */
class CreateKafkaConnectionRequestAllOf {
    /**
     * Constructs a new <code>CreateKafkaConnectionRequestAllOf</code>.
     * @alias module:model/CreateKafkaConnectionRequestAllOf
     * @param name {String} The name of the consumer
     * @param brokers {String} Kafka broker endpoints.
     * @param groupId {String} Group Id for connection
     * @param topic {String} Topic name
     * @param transformerId {String} The transformer to use, if empty the default system transformer will be used
     */
    constructor(name, brokers, groupId, topic, transformerId) { 
        
        CreateKafkaConnectionRequestAllOf.initialize(this, name, brokers, groupId, topic, transformerId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, brokers, groupId, topic, transformerId) { 
        obj['name'] = name;
        obj['brokers'] = brokers;
        obj['groupId'] = groupId;
        obj['topic'] = topic;
        obj['transformerId'] = transformerId;
    }

    /**
     * Constructs a <code>CreateKafkaConnectionRequestAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateKafkaConnectionRequestAllOf} obj Optional instance to populate.
     * @return {module:model/CreateKafkaConnectionRequestAllOf} The populated <code>CreateKafkaConnectionRequestAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateKafkaConnectionRequestAllOf();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('brokers')) {
                obj['brokers'] = ApiClient.convertToType(data['brokers'], 'String');
            }
            if (data.hasOwnProperty('groupId')) {
                obj['groupId'] = ApiClient.convertToType(data['groupId'], 'String');
            }
            if (data.hasOwnProperty('topic')) {
                obj['topic'] = ApiClient.convertToType(data['topic'], 'String');
            }
            if (data.hasOwnProperty('transformerId')) {
                obj['transformerId'] = ApiClient.convertToType(data['transformerId'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The name of the consumer
 * @member {String} name
 */
CreateKafkaConnectionRequestAllOf.prototype['name'] = undefined;

/**
 * The description of the consumer
 * @member {String} description
 */
CreateKafkaConnectionRequestAllOf.prototype['description'] = undefined;

/**
 * Kafka broker endpoints.
 * @member {String} brokers
 */
CreateKafkaConnectionRequestAllOf.prototype['brokers'] = undefined;

/**
 * Group Id for connection
 * @member {String} groupId
 */
CreateKafkaConnectionRequestAllOf.prototype['groupId'] = undefined;

/**
 * Topic name
 * @member {String} topic
 */
CreateKafkaConnectionRequestAllOf.prototype['topic'] = undefined;

/**
 * The transformer to use, if empty the default system transformer will be used
 * @member {String} transformerId
 */
CreateKafkaConnectionRequestAllOf.prototype['transformerId'] = undefined;






export default CreateKafkaConnectionRequestAllOf;

