/**
 * ZIQNI Admin API
 * Ziqni Application Services are used to manage and configure spaces.
 *
 * The version of the OpenAPI document: 3.0.7
 * Contact: support@ziqni.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DataSetsReference model module.
 * @module model/DataSetsReference
 * @version 0.0.26
 */
class DataSetsReference {
    /**
     * Constructs a new <code>DataSetsReference</code>.
     * The reference to the DataSets.
     * @alias module:model/DataSetsReference
     * @param key {String} Data set values to retrive from DataSets map of the response.
     */
    constructor(key) { 
        
        DataSetsReference.initialize(this, key);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, key) { 
        obj['key'] = key;
    }

    /**
     * Constructs a <code>DataSetsReference</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DataSetsReference} obj Optional instance to populate.
     * @return {module:model/DataSetsReference} The populated <code>DataSetsReference</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DataSetsReference();

            if (data.hasOwnProperty('style')) {
                obj['style'] = ApiClient.convertToType(data['style'], 'String');
            }
            if (data.hasOwnProperty('key')) {
                obj['key'] = ApiClient.convertToType(data['key'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The type of graph to inject the DataSets into.
 * @member {String} style
 */
DataSetsReference.prototype['style'] = undefined;

/**
 * Data set values to retrive from DataSets map of the response.
 * @member {String} key
 */
DataSetsReference.prototype['key'] = undefined;






export default DataSetsReference;

