openapi: 3.0.2
info:
  title: ZIQNI Admin API
  version: 3.0.14
  description: |-
    Ziqni Application Services are used to manage and configure spaces.
    
    Change log:
    
    2024-02-27 Added rewards reduced to the LeaderboardEntry response
  contact:
    name: Support Team
    url: 'https://www.ziqni.com/'
    email: support@ziqni.com
  license:
    name: Ziqni General Licence
    url: 'https://www.ziqni.com/terms-of-service/'
  x-logo:
    url: 'https://documentation.ziqni.com/ziqni-logo-white.png'
    backgroundColor: '#FFFFFF'
    altText: Ziqni
servers:
  -
    url: 'https://api.ziqni.com'
    description: Production environment
paths:
  /products/query:
    summary: Get products by query
    description: This operation allows you to get products in your project using a query.
    post:
      tags:
        - products
      security:
        -
          OAuth2:
            - ViewProducts
      operationId: getProductsByQuery
      summary: Get products by query
      description: >-
        Retrieve Products from Ziqni database by unique Product ID's or any other POST body parameters
        using the POST method
  /products/delete:
    summary: Delete products by query
    description: This operation allows you to delete products in your project using a query.
    post:
      tags:
        - products
      security:
        -
          OAuth2:
            - AdminProducts
      operationId: deleteProductsByQuery
      summary: Delete products by query
      description: >-
        Delete Products from Ziqni database by unique Product ID's or any other POST body parameters
        using the POST method
  /members/query:
    summary: Get members by query
    description: This operation allows you to get members in your project using a query.
    post:
      tags:
        - members
      security:
        -
          OAuth2:
            - ViewMembers
      operationId: getMembersByQuery
      summary: Get members by query
      description: >-
        Retrieve Members from Ziqni database by unique Member ID's or any other POST body parameters
        using the POST method
  /members/delete:
    summary: Delete members by query
    description: This operation allows you to delete members in your project using a query.
    post:
      tags:
        - members
      security:
        -
          OAuth2:
            - AdminMembers
      operationId: deleteMembersByQuery
      summary: Delete members by query
      description: >-
        Delete Members from Ziqni database by unique Members ID's or any other POST body parameters
        using the POST method
  /competitions/query:
    post:
      tags:
        - competitions
      security:
        -
          OAuth2:
            - ViewCompetitions
      operationId: getCompetitionsByQuery
      description: >-
        Retrieve Competitions from Ziqni database by unique Competition ID's or any other POST body
        parameters using the POST method
  /competitions/state:
    put:
      tags:
        - competitions
      security:
        -
          OAuth2:
            - ManageCompetition
      operationId: updateCompetitionsState
      description: Manages the Competitions state
  /contests/query:
    post:
      tags:
        - contests
      security:
        -
          OAuth2:
            - ViewContest
      operationId: getContestsByQuery
      description: >-
        Retrieve Contests from Ziqni database by unique Contests ID's or any other POST body
        parameters using the POST method
  '/contests/{id}/clone':
    get:
      tags:
        - contests
      security:
        -
          OAuth2:
            - ViewContest
      operationId: getContestsToClone
      description: Clones a Contest for the identifier provided
  /contests/state:
    put:
      tags:
        - contests
      security:
        -
          OAuth2:
            - ManageContest
      operationId: updateContestsState
      description: Manages the Contests state
  /achievements/query:
    post:
      tags:
        - achievements
      security:
        -
          OAuth2:
            - ViewAchievement
      operationId: getAchievementsByQuery
      description: >-
        Retrieve Achievements from Ziqni database by unique Achievements ID's or any other POST body
        parameters using the POST method
  /achievements/delete:
    post:
      tags:
        - achievements
      deprecated: true
      security:
        -
          OAuth2:
            - AdminAchievements
      operationId: deleteAchievementsByQuery
      description: >-
        Delete Achievements from Ziqni database by unique Achievements ID's or any other POST body
        parameters using the POST method
  '/achievements/{id}/issued':
    get:
      tags:
        - achievements
      security:
        -
          OAuth2:
            - ViewAchievement
      operationId: getIssuedAchievementsCountById
      description: Receive a count of Issued Achievements by identifier provided
  '/achievements/{id}/members':
    get:
      tags:
        - achievements
      security:
        -
          OAuth2:
            - ViewAchievement
      operationId: getMembersAchievementsDetails
      description: >-
        Receive a list of members that had an Achievement issued for the Achievement identified
        provided
  '/achievements/{id}/antecedents':
    get:
      tags:
        - achievements
      security:
        -
          OAuth2:
            - ViewAchievement
      operationId: getAntecendentsForAchievement
      summary: NOT AVAILABLE IN CURRENT RELEASE
      description: Receive a list of Antecedent Achievements for the Achievement identified provided
  '/achievements/{id}/clone':
    get:
      tags:
        - achievements
      security:
        -
          OAuth2:
            - ViewAchievement
      operationId: getAchievementToClone
      description: Clones an Achievement for the identifier provided
  /achievements/state:
    put:
      tags:
        - achievements
      security:
        -
          OAuth2:
            - ManageAchievements
      operationId: updateAchievementsLiveStatus
      description: 'Manage the state of achievement - Draft, Live, Archived'
  /rewards/query:
    post:
      tags:
        - rewards
      security:
        -
          OAuth2:
            - ViewRewards
      operationId: getRewardsByQuery
      description: >-
        Retrieve Rewards from Ziqni database by unique Rewards ID's or any other POST body parameters
        using the POST method
  /rewards/delete:
    post:
      tags:
        - rewards
      security:
        -
          OAuth2:
            - AdminRewards
      operationId: deleteRewardsByQuery
      description: >-
        Delete Rewards from Ziqni database by unique Rewards ID's or any other POST body parameters
        using the POST method
  /awards/claim:
    put:
      tags:
        - awards
      security:
        -
          OAuth2:
            - AdminClaim
      operationId: claimAwards
      description: Claim Awards that need to be actioned at
  /reward-types/query:
    summary: Get reward types by query
    description: This operation allows you to get reward types in your project using a query.
    post:
      tags:
        - reward-types
      security:
        -
          OAuth2:
            - ViewRewardType
      operationId: getRewardTypesByQuery
      summary: Get reward types by query
      description: >-
        Retrieve Reward types from Ziqni database by unique Reward type ID's or any other POST body
        parameters using the POST method
  /reward-types/delete:
    summary: Delete reward types by query
    description: This operation allows you to delete reward types in your project using a query.
    post:
      tags:
        - reward-types
      security:
        -
          OAuth2:
            - AdminRewardType
      operationId: deleteRewardTypesByQuery
      summary: Delete reward types by query
      description: >-
        Delete Reward types from Ziqni database by unique Reward types ID's or any other POST body
        parameters using the POST method
  /action-types/query:
    summary: Get action types by query
    description: This operation allows you to get action types in your project using a query.
    post:
      tags:
        - action-types
      security:
        -
          OAuth2:
            - ViewActions
      operationId: getActionTypesByQuery
      summary: Get action types by query
      description: >-
        Retrieve Action types from Ziqni database by unique Action type ID's or any other POST body
        parameters using the POST method
  /action-types/delete:
    summary: Delete action types by query
    description: This operation allows you to delete action types in your project using a query.
    post:
      tags:
        - action-types
      security:
        -
          OAuth2:
            - AdminActions
      operationId: deleteActionTypesByQuery
      summary: Delete action types by query
      description: >-
        Delete Action types from Ziqni database by unique Action types ID's or any other POST body
        parameters using the POST method
  /languages/query:
    post:
      tags:
        - languages
      security:
        -
          OAuth2:
            - ViewLanguage
      operationId: getLanguagesByQuery
      description: >-
        Retrieve Languages from Ziqni database by unique Language ID's or any other POST body
        parameters using the POST method
  /languages/delete:
    post:
      tags:
        - languages
      security:
        -
          OAuth2:
            - AdminLanguage
      operationId: deleteLanguagesByQuery
      description: >-
        Delete Languages from Ziqni database by unique Language ID's or any other POST body parameters
        using the POST method
  /custom-fields/query:
    summary: Get custom fields by query
    description: This operation allows you to get custom fields in your project using a query.
    post:
      tags:
        - custom-fields
      security:
        -
          OAuth2:
            - ViewCustomFields
      operationId: getCustomFieldsByQuery
      summary: Get custom fields by query
      description: >-
        Retrieve Custom fields from Ziqni database by unique Custom field ID's or any other POST body
        parameters using the POST method
  /custom-fields/delete:
    summary: Delete custom fields by query
    description: This operation allows you to delete custom fields in your project using a query.
    post:
      tags:
        - custom-fields
      security:
        -
          OAuth2:
            - AdminCustomFields
      operationId: deleteCustomFieldsByQuery
      summary: Delete custom fields by query
      description: >-
        Delete Custom fields from Ziqni database by unique Custom field ID's or any other POST body
        parameters using the POST method
  /units-of-measure/query:
    post:
      tags:
        - units-of-measure
      security:
        -
          OAuth2:
            - ViewUOM
      operationId: getUnitsOfMeasureByQuery
      description: >-
        Retrieve Units of measure from Ziqni database by unique Unit of measure ID's or any other POST
        body parameters using the POST method
  /units-of-measure/delete:
    post:
      tags:
        - units-of-measure
      security:
        -
          OAuth2:
            - AdminUOM
      operationId: deleteUnitsOfMeasureByQuery
      summary: Delete units of measure by query
      description: >-
        Delete Units of measure from Ziqni database by unique Unit of measure ID's or any other POST
        body parameters using the POST method
  /transformers/query:
    post:
      tags:
        - transformers
      security:
        -
          OAuth2:
            - AdminTransformers
      operationId: getTransformersByQuery
      description: >-
        Retrieve a Transformer or a list of Transformers from Ziqni by unique Transformer ID's or any
        other POST body parameters using the POST method
  /webhooks/query:
    post:
      tags:
        - webhooks
      security:
        -
          OAuth2:
            - AdminWebhooks
      operationId: getWebhooksByQuery
      description: >-
        Retrieve a Webhook or a list of Webhooks from Ziqni by unique Webhook ID's or any other POST
        body parameters using the POST method
  /webhooks/delete:
    post:
      tags:
        - webhooks
      security:
        -
          OAuth2:
            - AdminWebhooks
      operationId: deleteWebhooksByQuery
      summary: Delete webhooks by query
      description: >-
        Delete a Webhook or a list of Webhooks from Ziqni by unique Webhook ID's or any other POST
        body parameters using the POST method
  /events/query:
    post:
      tags:
        - events
      security:
        -
          OAuth2:
            - ViewEvents
      operationId: getEventsByQuery
      description: >-
        Retrieve an Event or a list of Events from Ziqni by unique Event ID's or any other POST body
        parameters using the POST method
  /api-keys/query:
    summary: Get api keys by query
    description: This operation allows you to get api keys in your project using a query.
    post:
      tags:
        - api-keys
      security:
        -
          OAuth2:
            - AdminApi
      operationId: getApiKeysByQuery
      summary: Get api keys by query
      description: Retrieve an Api key or a list of Api keys by query
  /api-keys/delete:
    summary: Delete api keys by query
    description: This operation allows you to delete api keys in your project using a query.
    post:
      tags:
        - api-keys
      security:
        -
          OAuth2:
            - AdminApi
      operationId: deleteApiKeysByQuery
      summary: Delete api keys by query
      description: Delete an Api key or a list of Api keys from Ziqni by query
  '/api-keys/{id}':
    summary: Get and delete api keys by id
    description: These operations allow you to get or delete api keys in your project by id.
    get:
      tags:
        - api-keys
      security:
        -
          OAuth2:
            - AdminApi
      operationId: getApiKeysById
      summary: Get api keys by id
      description: >-
        Returns an Api key by identifier provided. This assumes that api keys have first been created
        via a POST request or web console
    delete:
      tags:
        - api-keys
      security:
        -
          OAuth2:
            - AdminApi
      operationId: deleteApiKeysById
      summary: Delete api keys by id
      description: Delete the Api key for a given identifier specified
  /tags/delete:
    summary: Delete tags by query
    description: This operation allows you to delete tags by query
    post:
      tags:
        - tags
      security:
        -
          OAuth2:
            - AdminTags
      operationId: deleteTagsByQuery
      summary: Delete tags by query
      description: >-
        Delete Tags from Ziqni database by unique Tags ID's or any other POST body parameters using
        the POST method
  /connections/state:
    summary: Manage connection states
    description: >-
      The endpoint provides a means to manage connection state, for example: Start a conneciton or Stop
      a connection.
    post:
      tags:
        - connections
      deprecated: false
      security:
        -
          OAuth2:
            - AdminConsumer
      operationId: updateConnectionsState
      summary: Update connection status
      description: Update the state of a Consumer using the POST method
  /languages/available:
    get:
      tags:
        - languages
      security:
        -
          OAuth2:
            - ViewLanguage
      operationId: getListOfAllLanguages
      description: Returns a list of all avaialable Languages
  '/spaces/{spaceName}':
    get:
      tags:
        - spaces
      security:
        -
          OAuth2:
            - ViewSpaces
      operationId: getSpacesByName
      description: Return a list of sub-spaces for the given Space Name provided
    delete:
      tags:
        - spaces
      security:
        -
          OAuth2:
            - AdminSpaces
      operationId: deleteSpaces
      summary: NOT AVAILABLE IN CURRENT RELEASE
      description: Delete the Space for the given Space Name provided
  /collaborators/available-roles:
    get:
      tags:
        - collaborators
      security:
        -
          OAuth2:
            - ViewCollaborator
      operationId: getAvailableRolesForCollaborators
      description: >-
        Returns a list of Collaborators. This assumes that Users have first been uploaded via a POST
        request or web console
  /webhooks/triggers:
    get:
      tags:
        - webhooks
      security:
        -
          OAuth2:
            - AdminWebhooks
      operationId: getWebhooksTriggers
      description: Returns a list of all avilable Webhooks triggers
  /members/find-by-ref-identifiers:
    summary: Get products by reference identifiers
    description: This operation allows you to get members in your project using reference identifiers.
    get:
      tags:
        - members
      security:
        -
          OAuth2:
            - ViewMembers
      operationId: getMembersByRefId
      summary: Get members by reference ids
      description: >-
        Returns a list of Members. This assumes that members have first been uploaded via a POST
        request or web console
  /rules/schema:
    get:
      tags:
        - rules
      security:
        -
          OAuth2:
            - ViewRules
      operationId: getRuleSchemas
      description: >-
        Returns a list of rules. This assumes that rules have first been created during achievement,
        competition or contest setup
  /rules/validate:
    post:
      tags:
        - rules
      security:
        -
          OAuth2:
            - ManageRules
      operationId: validateRules
      description: Validate rules
  /rules/operand-lookup:
    post:
      tags:
        - rules
      security:
        -
          OAuth2:
            - ManageRules
      operationId: lookupOperandsRules
      description: Search or get rule operand values
  /rules/delete:
    post:
      tags:
        - rules
      security:
        -
          OAuth2:
            - AdminRewards
      operationId: deleteRulesByQuery
      description: >-
        Delete Rules from Ziqni database by unique Rules ID's or any other POST body parameters using
        the POST method
  /rules/query:
    post:
      tags:
        - rules
      security:
        -
          OAuth2:
            - ViewRules
      operationId: getRulesByQuery
      description: >-
        Retrieve Rules from Ziqni database by unique Rewards ID's or any other POST body parameters
        using the POST method
  /tags/query:
    summary: Get tags by query
    description: This operation allows you to get tags by query
    post:
      tags:
        - tags
      security:
        -
          OAuth2:
            - ViewTags
      operationId: getTagsByQuery
      summary: Get tags by query
      description: >-
        Retrieve Tags from Ziqni database by unique Tags ID's or any other POST body parameters using
        the POST method
  /account-messages/delete:
    post:
      tags:
        - account-messages
      security:
        -
          OAuth2:
            - AdminMessages
      operationId: deleteAccountMessagesByQuery
      description: Delete Account Messages from the system by query.
  /account-messages/query:
    post:
      tags:
        - account-messages
      security:
        -
          OAuth2:
            - ViewMessages
      operationId: getAccountMessagesByQuery
      description: Retrieve Account Messages from the system by query.
  /member-messages/delete:
    post:
      tags:
        - member-messages
      security:
        -
          OAuth2:
            - AdminMessages
      operationId: deleteMemberMessagesByQuery
      description: Delete Member Messages by query.
  /member-messages/query:
    post:
      tags:
        - member-messages
      security:
        -
          OAuth2:
            - ViewMessages
      operationId: getMemberMessagesByQuery
      description: >-
        Retrieve Member Messages from Ziqni database by unique message ID's or any other POST body
        parameters using the POST method
  /notifications/delete:
    post:
      tags:
        - notifications
      security:
        -
          OAuth2:
            - AdminMessages
      operationId: deleteNotificationsByQuery
      description: >-
        Delete Notification Messages from Ziqni database by unique message ID's or any other POST body
        parameters using the POST method
  /notifications/query:
    post:
      tags:
        - notifications
      security:
        -
          OAuth2:
            - ViewMessages
      operationId: getNotificationsByQuery
      description: >-
        Retrieve Notification Messages from Ziqni database by unique message ID's or any other POST
        body parameters using the POST method
  /products:
    summary: Manage products
    description: These operations allow you to manage products in your project.
    get:
      tags:
        - products
      security:
        -
          OAuth2:
            - ViewProducts
      operationId: getProducts
      summary: Get products
      description: >-
        Returns a list of Products. This assumes that products have first been uploaded via a POST
        request or web console
      x-vue-item: Product
      x-vue-list: Products
    put:
      tags:
        - products
      security:
        -
          OAuth2:
            - ManageProducts
      operationId: updateProducts
      summary: Update products
      description: Update existing Products in the Ziqni database
    post:
      tags:
        - products
      security:
        -
          OAuth2:
            - AdminProducts
      operationId: createProducts
      summary: Create products
      description: Create new Products in the Ziqni database
    delete:
      tags:
        - products
      security:
        -
          OAuth2:
            - AdminProducts
      operationId: deleteProducts
      summary: Delete products
      description: Delete Products for a given identifier specified
  /account-messages:
    get:
      tags:
        - account-messages
      security:
        -
          OAuth2:
            - ViewMessages
      operationId: getAccountMessages
      description: Returns a list of Account Messages.
      x-vue-item: AccountMessage
      x-vue-list: AccountMessages
    delete:
      tags:
        - account-messages
      security:
        -
          OAuth2:
            - ManageMessages
      operationId: deleteAccountMessages
      description: Delete Account Messages for a given identifier specified
  /achievements:
    summary: Achievements in the system.
    get:
      tags:
        - achievements
      security:
        -
          OAuth2:
            - ViewAchievement
      operationId: getAchievements
      summary: Get Achievements
      description: >-
        Returns a list of Achievements. This assumes that achievements have first been uploaded via a
        POST request or web console
      x-vue-item: Achievement
      x-vue-list: Achievements
    put:
      tags:
        - achievements
      security:
        -
          OAuth2:
            - ManageAchievements
      operationId: updateAchievements
      summary: Update Achievements
      description: Update existing Achievements in the Ziqni database
    post:
      tags:
        - achievements
      security:
        -
          OAuth2:
            - ManageAchievements
      operationId: createAchievements
      summary: Create Achievements
      description: Create Achievements in the Ziqni database
    delete:
      tags:
        - achievements
      deprecated: true
      security:
        -
          OAuth2:
            - ManageAchievements
      operationId: deleteAchievements
      summary: Delete Achievements
      description: Delete Achievements for a given identifier specified
  /action-types:
    summary: Manage action types
    description: These operations allow you to manage action types in your project.
    get:
      tags:
        - action-types
      security:
        -
          OAuth2:
            - ViewActions
      operationId: getActionTypes
      summary: Get action types
      description: >-
        Returns a list of Action Types. This assumes that action types have first been uploaded via a
        POST request or web console
      x-vue-item: ActionType
      x-vue-list: ActionTypes
    put:
      tags:
        - action-types
      security:
        -
          OAuth2:
            - AdminActions
      operationId: updateActionTypes
      summary: Update action types
      description: Update existing Action types in the Ziqni database
    post:
      tags:
        - action-types
      security:
        -
          OAuth2:
            - AdminActions
      operationId: createActionTypes
      summary: Create action types
      description: Create new Action types in the Ziqni database
    delete:
      tags:
        - action-types
      security:
        -
          OAuth2:
            - AdminActions
      operationId: deleteActionTypes
      summary: Delete action types
      description: Delete Action types for a given identifier specified
  /collaborators:
    get:
      tags:
        - collaborators
      security:
        -
          OAuth2:
            - AdminCollaborator
      operationId: getCollaborators
      description: >-
        Returns a list of Collaborators. This assumes that Users have first been uploaded via a POST
        request or web console
      x-vue-item: Collaborator
      x-vue-list: Collaborators
    put:
      tags:
        - collaborators
      security:
        -
          OAuth2:
            - AdminCollaborator
      operationId: updateCollaborators
      description: Update an existing Collaborator in the Ziqni system
    post:
      tags:
        - collaborators
      security:
        -
          OAuth2:
            - AdminCollaborator
      operationId: createCollaborators
      description: Create a new Collaborator in the Ziqni
    delete:
      tags:
        - collaborators
      security:
        -
          OAuth2:
            - AdminCollaborator
      operationId: deleteCollaborators
      description: >-
        Returns a list of Collaborators. This assumes that Users have first been uploaded via a POST
        request or web console
  /competitions:
    get:
      tags:
        - competitions
      security:
        -
          OAuth2:
            - ViewCompetitions
      operationId: getCompetitions
      description: >-
        Returns a list of Competitions. This assumes that competitions have first been uploaded via a
        POST request or web console
      x-vue-item: Competition
      x-vue-list: Competitions
    put:
      tags:
        - competitions
      security:
        -
          OAuth2:
            - ManageCompetition
      operationId: updateCompetitions
      description: Update an existing Competition in the Ziqni database
    post:
      tags:
        - competitions
      security:
        -
          OAuth2:
            - ManageCompetition
      operationId: createCompetitions
      description: Create a new Competition in the Ziqni database
  /contests:
    get:
      tags:
        - contests
      security:
        -
          OAuth2:
            - ViewContest
      operationId: getContests
      description: >-
        Returns a list of Contests. This assumes that contests have first been uploaded via a POST
        request or web console
      x-vue-item: Contest
      x-vue-list: Contests
    put:
      tags:
        - contests
      security:
        -
          OAuth2:
            - ManageContest
      operationId: updateContest
      description: Update an existing Contest in the Ziqni database
    post:
      tags:
        - contests
      security:
        -
          OAuth2:
            - ManageContest
      operationId: createContests
      description: Create a new Contests in the Ziqni database
  /custom-fields:
    summary: Manage custom fields
    description: These operations allow you to manage custom fields in your project.
    get:
      tags:
        - custom-fields
      security:
        -
          OAuth2:
            - ViewCustomFields
      operationId: getCustomFields
      summary: Get custom fields
      description: >-
        Returns a list of Custom fields. This assumes that custom fields have first been uploaded via
        a POST request or web console
      x-vue-item: CustomField
      x-vue-list: CustomFields
    put:
      tags:
        - custom-fields
      security:
        -
          OAuth2:
            - AdminCustomFields
      operationId: updateCustomFields
      summary: Update custom fields
      description: Update existing Custom fields in the Ziqni database
    post:
      tags:
        - custom-fields
      security:
        -
          OAuth2:
            - AdminCustomFields
      operationId: createCustomFields
      summary: Create custom fields
      description: Create new Custom fields in the Ziqni database
    delete:
      tags:
        - custom-fields
      security:
        -
          OAuth2:
            - AdminCustomFields
      operationId: deleteCustomFields
      summary: Delete custom fields
      description: Delete the Custom fields for a given identifier specified
  /events:
    get:
      tags:
        - events
      security:
        -
          OAuth2:
            - ViewEvents
      operationId: getEvents
      description: >-
        Retrieve an Event or a list of Events from Ziqni by unique Event ID's or any other POST body
        parameters using the POST method
      x-vue-item: Event
      x-vue-list: Events
    post:
      tags:
        - events
      security:
        -
          OAuth2:
            - AdminEvents
      operationId: createEvents
      description: Create an Event
  /languages:
    get:
      tags:
        - languages
      security:
        -
          OAuth2:
            - ViewLanguage
      operationId: getLanguages
      description: >-
        Returns a list of Languages available in the space. This assumes that languages have first
        been uploaded via a POST request or web console
      x-vue-item: Language
      x-vue-list: Languages
    put:
      tags:
        - languages
      security:
        -
          OAuth2:
            - AdminLanguage
      operationId: updateLanguages
      description: Update an existing Language in the Ziqni database
    post:
      tags:
        - languages
      security:
        -
          OAuth2:
            - AdminLanguage
      operationId: createLanguages
      description: Create a new Language in the Ziqni database
    delete:
      tags:
        - languages
      security:
        -
          OAuth2:
            - AdminLanguage
      operationId: deleteLanguages
      description: Delete Languages for a given identifier specified
  /member-messages:
    get:
      tags:
        - member-messages
      security:
        -
          OAuth2:
            - ViewMessages
      operationId: getMemberMessages
      description: >-
        Returns a list of Member Messages. This assumes that Messages have first been uploaded via a
        POST request or web console
      x-vue-item: MemberMessage
      x-vue-list: MemberMessages
    post:
      tags:
        - member-messages
      security:
        -
          OAuth2:
            - ManageMessages
      operationId: createMemberMessages
      description: Create Member Messages in the Ziqni database
    delete:
      tags:
        - member-messages
      security:
        -
          OAuth2:
            - ManageMessages
      operationId: deleteMemberMessages
      description: Delete Member Messages for a given identifier specified
  /notifications:
    get:
      tags:
        - notifications
      security:
        -
          OAuth2:
            - ViewMessages
      operationId: getNotifications
      description: >-
        Returns a list of Notification Messages. This assumes that Messages have first been uploaded
        via a POST request or web console
      x-vue-item: Notification
      x-vue-list: Notifications
    post:
      tags:
        - notifications
      security:
        -
          OAuth2:
            - ManageMessages
      operationId: createNotifications
      description: Create Notification Messages in the Ziqni database
    delete:
      tags:
        - notifications
      security:
        -
          OAuth2:
            - ManageMessages
      operationId: deleteNotifications
      description: Delete Notification Messages for a given identifier specified
  /rewards:
    get:
      tags:
        - rewards
      security:
        -
          OAuth2:
            - ViewRewards
      operationId: getRewards
      description: >-
        Returns a list of Rewards. This assumes that rewards have first been uploaded via a POST
        request or web console
      x-vue-item: Reward
      x-vue-list: Rewards
    put:
      tags:
        - rewards
      security:
        -
          OAuth2:
            - ManageRewards
      operationId: updateRewards
      description: Update existing Rewards in the Ziqni database
    post:
      tags:
        - rewards
      security:
        -
          OAuth2:
            - ManageRewards
      operationId: createRewards
      description: Create Rewards in the Ziqni database
    delete:
      tags:
        - rewards
      security:
        -
          OAuth2:
            - ManageRewards
      operationId: deleteRewards
      description: Delete Rewards for a given identifier specified
  /rules:
    get:
      tags:
        - rules
      security:
        -
          OAuth2:
            - ViewRules
      operationId: getRules
      description: >-
        Returns a list of rules. This assumes that rules have first been created during achievement,
        competition or contest setup. The id is the ID of the entity the rules describe
      x-vue-item: Rule
      x-vue-list: Rules
    put:
      tags:
        - rules
      security:
        -
          OAuth2:
            - ManageRules
      operationId: updateRules
      description: Update existing rules
  /spaces:
    get:
      tags:
        - spaces
      security:
        -
          OAuth2:
            - ViewSpaces
      operationId: getSpaceInfromation
      description: Returns a list of Spaces for the current session
      x-vue-item: Space
      x-vue-list: Spaces
    put:
      tags:
        - spaces
      security:
        -
          OAuth2:
            - AdminSpaces
      operationId: updateSpace
      description: Update a  Space for the user in the Ziqni
    post:
      tags:
        - spaces
      security:
        -
          OAuth2:
            - ViewSpaces
      operationId: createSpace
      description: Create a new Space for the user in the Ziqni
    delete:
      operationId: deleteSpace
      summary: NOT AVAILABLE IN CURRENT RELEASE
  /tags:
    summary: Manage tags
    description: These operations allow you to manage tags in your project.
    get:
      tags:
        - tags
      security:
        -
          OAuth2:
            - ViewTags
      operationId: getTags
      summary: Get tags
      description: >-
        Returns a list of Tags. This assumes that tags have first been uploaded via a POST request or
        web console
      x-vue-item: Tag
      x-vue-list: Tags
    put:
      tags:
        - tags
      security:
        -
          OAuth2:
            - ManageTags
      operationId: updateTags
      summary: Update tags
      description: Update existing Tags in the Ziqni database
    post:
      tags:
        - tags
      security:
        -
          OAuth2:
            - ManageTags
      operationId: createTags
      summary: Create tags
      description: Create new Tags in the Ziqni database
    delete:
      tags:
        - tags
      security:
        -
          OAuth2:
            - AdminTags
      operationId: deleteTags
      summary: Delete tags
      description: Delete Tags for a given identifier specified
  /transformers:
    get:
      tags:
        - transformers
      security:
        -
          OAuth2:
            - AdminTransformers
      operationId: getTransformers
      description: >-
        Returns a list of Transformers. This assumes that transformers have first been uploaded via a
        POST request or web console
      x-vue-item: Transformer
      x-vue-list: Transformers
    put:
      tags:
        - transformers
      security:
        -
          OAuth2:
            - AdminTransformers
      operationId: updateTransformers
      description: Update an existing Transformer in the Ziqni system
    post:
      tags:
        - transformers
      security:
        -
          OAuth2:
            - AdminTransformers
      operationId: createTransformers
      description: Create a new Transformer in the Ziqni system
    delete:
      tags:
        - transformers
      security:
        -
          OAuth2:
            - AdminTransformers
      operationId: deleteTransformers
      description: Delete the Transformers for a given identifier specified
  /units-of-measure:
    get:
      tags:
        - units-of-measure
      security:
        -
          OAuth2:
            - ViewUOM
      operationId: getUnitsOfMeasure
      description: >-
        Returns a list of Units of measure. This assumes that units of measure have first been
        uploaded via a POST request or web console
      x-vue-item: UnitOfMeasure
      x-vue-list: UnitsOfMeasure
    put:
      tags:
        - units-of-measure
      security:
        -
          OAuth2:
            - ManageUOM
      operationId: updateUnitsOfMeasure
      description: Update an existing Unit of measure in the Ziqni database
    post:
      tags:
        - units-of-measure
      security:
        -
          OAuth2:
            - AdminUOM
      operationId: createUnitsOfMeasure
      description: Create a new Unit of measure in the Ziqni database
    delete:
      tags:
        - units-of-measure
      security:
        -
          OAuth2:
            - AdminUOM
      operationId: deleteUnitsOfMeasure
      description: Delete the Unit of measured for a given identifier specified
  /user:
    get:
      tags:
        - user
      security:
        -
          OAuth2:
            - ViewUser
      operationId: getUser
      description: >-
        Returns the current users user. This assumes that a user has first been uploaded via a POST
        request or web console
      x-vue-item: User
      x-vue-list: Users
  /webhooks:
    get:
      tags:
        - webhooks
      security:
        -
          OAuth2:
            - AdminWebhooks
      operationId: getWebhooks
      description: Returns a list of Webhooks.
      x-vue-item: Webhook
      x-vue-list: Webhooks
    put:
      tags:
        - webhooks
      security:
        -
          OAuth2:
            - AdminWebhooks
      operationId: updateWebhooks
      description: Update an existing Webhook in the Ziqni system
    post:
      tags:
        - webhooks
      security:
        -
          OAuth2:
            - AdminWebhooks
      operationId: createWebhooks
      description: Create a new Webhook in the Ziqni system
    delete:
      tags:
        - webhooks
      security:
        -
          OAuth2:
            - AdminWebhooks
      operationId: deleteWebhooks
      description: Delete the Webhooks for a given identifier specified
  /reward-types:
    summary: Manage reward types
    description: These operations allow you to manage reward types in your project.
    get:
      tags:
        - reward-types
      security:
        -
          OAuth2:
            - ViewRewardType
      operationId: getRewardTypes
      summary: Get reward types
      description: >-
        Returns a list of Reward Types. This assumes that reward types have first been uploaded via a
        POST request or web console
      x-vue-item: RewardType
      x-vue-list: RewardTypes
    put:
      tags:
        - reward-types
      security:
        -
          OAuth2:
            - ManageRewardType
      operationId: updateRewardTypes
      summary: Update Reward Types
      description: Update existing Reward types in the Ziqni database
    post:
      tags:
        - reward-types
      security:
        -
          OAuth2:
            - ManageRewardType
      operationId: createRewardTypes
      summary: Create reward types
      description: Create new Reward types in the Ziqni database
    delete:
      tags:
        - reward-types
      security:
        -
          OAuth2:
            - AdminRewardType
      operationId: deleteRewardTypes
      summary: Delete reward types
      description: Delete Reward types for a given identifier specified
  /awards/query:
    post:
      tags:
        - awards
      security:
        -
          OAuth2:
            - ViewAwards
      operationId: getAwardsByQuery
      description: >-
        Retrieve Awards from Ziqni database by unique Awards ID's or any other POST body parameters
        using the POST method
  /products/find-by-ref-identifiers/:
    summary: Get products by reference identifiers
    description: This operation allows you to get products in your project using reference identifiers.
    get:
      tags:
        - products
      security:
        -
          OAuth2:
            - ViewProducts
      operationId: getProductsByRefId
      summary: Get products by reference ids
      description: >-
        Returns a list of Products. This assumes that products have first been uploaded via a POST
        request or web console
  /compute-engines:
    get:
      tags:
        - compute-engine
      security:
        -
          OAuth2:
            - AdminApi
      operationId: getComputeEngines
      description: >-
        Returns a list of Compute Engines. This assumes that api keys have first been created via a
        POST request or web console
      x-vue-item: ComputeEngine
      x-vue-list: ComputeEngines
    put:
      tags:
        - compute-engine
      security:
        -
          OAuth2:
            - AdminApi
      operationId: updateComputeEngines
      description: Update an existing Compute Engine in the Ziqni system
    post:
      tags:
        - compute-engine
      security:
        -
          OAuth2:
            - AdminApi
      operationId: createComputeEngines
      description: Create a new Compute Engine in the Ziqni system
  '/compute-engines/{id}':
    get:
      tags:
        - compute-engine
      security:
        -
          OAuth2:
            - AdminApi
      operationId: getComputeEnginesById
      description: >-
        Returns an Compute Engine by identifier provided. This assumes that compute engines have first
        been created via a POST request or web console
    delete:
      tags:
        - compute-engine
      security:
        -
          OAuth2:
            - AdminApi
      operationId: deleteComputeEnginesById
      description: Delete the Compute Engine for a given identifier specified
  /compute-engines/delete:
    post:
      tags:
        - compute-engine
      security:
        -
          OAuth2:
            - AdminApi
      operationId: deleteComputeEnginesByQuery
      description: Delete an Compute Engine or a list of Compute Engines from Ziqni by query
  /compute-engines/query:
    post:
      tags:
        - compute-engine
      security:
        -
          OAuth2:
            - AdminApi
      operationId: getComputeEnginesByQuery
      description: Retrieve an Compute Engine or a list of Compute Engines by query
  /translations/find-by-entity-id:
    get:
      tags:
        - translations
      security:
        -
          OAuth2:
            - ViewTranslations
      operationId: getTranslationsByEntityId
      description: >-
        Returns a list of Translations. This assumes that translations have first been uploaded via a
        POST request or web console
  /transformers/delete:
    post:
      tags:
        - transformers
      security:
        -
          OAuth2:
            - AdminTransformers
      operationId: deleteTransformersByQuery
      description: >-
        Delete a Transformer or a list of Transformers from Ziqni by unique Transformer ID's or any
        other POST body parameters using the POST method
  /translations/delete:
    post:
      tags:
        - translations
      security:
        -
          OAuth2:
            - AdminTranslations
      operationId: deleteTranslationsByQuery
      summary: Delete translations by query
      description: >-
        Delete a Translation or a list of Translations from Ziqni by unique Translation ID's or any
        other POST body parameters using the POST method
  /translations/query:
    post:
      tags:
        - translations
      security:
        -
          OAuth2:
            - AdminTranslations
      operationId: getTranslationsByQuery
      description: >-
        Retrieve a Translation or a list of Translations from Ziqni by unique Translation ID's or any
        other POST body parameters using the POST method
  /translations:
    get:
      tags:
        - translations
      security:
        -
          OAuth2:
            - ViewTranslations
      operationId: getTranslations
      description: >-
        Returns a list of translations. This assumes that rules have first been created during
        achievement, competition or contest setup. The id is the ID of the entity the translations
        describe
      x-vue-item: Translation
      x-vue-list: Translations
    put:
      tags:
        - translations
      security:
        -
          OAuth2:
            - ManageTranslations
      operationId: updateTranslations
      description: Update existing translations
    post:
      tags:
        - translations
      operationId: createTranslations
      summary: creating a translation
      description: Create a new Translation in the Ziqni system
    delete:
      tags:
        - translations
      security:
        -
          OAuth2:
            - AdminTranslations
      operationId: deleteTranslations
      description: Delete the Translations for a given identifier specified
  /file-repositories/delete:
    post:
      tags:
        - file-repositories
      security:
        -
          OAuth2:
            - ManageFileObjectRep
      operationId: deleteFileRepositoriesByQuery
      description: >-
        Delete repositories nby query. Delete repositories by query and/or unique repository ID's or
        any other body parameters
  /file-repositories/query:
    post:
      tags:
        - file-repositories
      security:
        -
          OAuth2:
            - ManageFileObjectRep
      operationId: getFileRepositoriesByQuery
      description: Find file object repositories by query
  /file-repositories:
    get:
      tags:
        - file-repositories
      security:
        -
          OAuth2:
            - ManageFileObjectRep
      operationId: getFileRepositories
      description: >-
        Returns a list of file object repositories. This assumes that repositories have first been
        uploaded via a POST request or web console
      x-vue-item: FileRepository
      x-vue-list: FileRepositories
    put:
      tags:
        - file-repositories
      security:
        -
          OAuth2:
            - ManageFileObjectRep
      operationId: updateFileRepositories
      description: Update a file object repository in your Ziqni space.
    post:
      tags:
        - file-repositories
      security:
        -
          OAuth2:
            - ManageFileObjectRep
      operationId: createFileRepositories
      description: Create a new file object repository in your Ziqni space
    delete:
      tags:
        - file-repositories
      security:
        -
          OAuth2:
            - ManageFileObjectRep
      operationId: deleteFileRepositories
      description: Delete the file repository for a given identifier specified
  /file-objects:
    get:
      tags:
        - file-objects
      security:
        -
          OAuth2:
            - ViewObjects
      operationId: getFileObjects
      description: Returns a list of file objects
      x-ws-ignore: true
      x-vue-item: FileObject
      x-vue-list: FileObjects
    put:
      tags:
        - file-objects
      security:
        -
          OAuth2:
            - ManageObjects
      operationId: updateFileObjects
      x-ws-ignore: true
    post:
      tags:
        - file-objects
      security:
        -
          OAuth2:
            - ManageObjects
      operationId: createFileObjects
      x-ws-ignore: true
    delete:
      tags:
        - file-objects
      security:
        -
          OAuth2:
            - ManageObjects
      operationId: deleteFileObjects
      x-ws-ignore: true
  /file-objects/delete:
    post:
      tags:
        - file-objects
      security:
        -
          OAuth2:
            - AdminObjects
      operationId: deleteFileObjectsByQuery
      description: Delete file objects by query
      x-ws-ignore: true
  /file-objects/download:
    get:
      tags:
        - file-objects
      security:
        -
          OAuth2:
            - ManageObjects
      operationId: downloadFileObjects
      description: Download file objects from your Ziqni space
  /file-objects/query:
    post:
      tags:
        - file-objects
      security:
        -
          OAuth2:
            - ViewObjects
      operationId: getFileObjectsByQuery
      description: Retrieve file objects by query
      x-ws-ignore: true
  /file-objects/upload:
    post:
      tags:
        - file-objects
      security:
        -
          OAuth2:
            - ManageObjects
      operationId: uploadFileObjects
      description: Create or update file objects and binaries in your Ziqni space
      x-ws-ignore: true
  /competitions/simple:
    post:
      tags:
        - competitions
      security:
        -
          OAuth2:
            - ManageCompetition
      operationId: createSimpleCompetitions
      description: Create a Simple Competition in the Ziqni database
  /file-objects/save-template:
    post:
      tags:
        - file-objects
      security:
        -
          OAuth2:
            - ManageObjects
      operationId: saveTemplates
      description: Create or update file objects and binaries in your Ziqni space
      x-ws-ignore: true
  /api-keys:
    summary: Manage api keys
    description: These operations allow you to manage api keys in your project.
    get:
      tags:
        - api-keys
      security:
        -
          OAuth2:
            - AdminApi
      operationId: getApiKeys
      summary: Get api keys
      description: >-
        Returns a list of Api keys. This assumes that api keys have first been created via a POST
        request or web console
      x-vue-item: ApiKey
      x-vue-list: ApiKeys
    put:
      tags:
        - api-keys
      security:
        -
          OAuth2:
            - AdminApi
      operationId: updateApiKeys
      summary: Update api keys
      description: Update an existing Api key in the Ziqni system
    post:
      tags:
        - api-keys
      security:
        -
          OAuth2:
            - AdminApi
      operationId: createApiKeys
      summary: Delete api keys
      description: Create a new Api key in the Ziqni system
    delete:
      tags:
        - api-keys
      security:
        -
          OAuth2:
            - AdminActions
      operationId: deleteApiKeys
      summary: Delete api keys
      description: Delete Api keys for a given identifier specified
  '/contests/{id}/leaderboard':
    get:
      tags:
        - contests
      deprecated: true
      security:
        -
          OAuth2:
            - ViewContest
      operationId: getContestsLeaderboardById
      description: 'Use /leadeboard instead, Returns a leaderborad for the Contests id provided'
  '/competitions/{id}/clone':
    get:
      tags:
        - competitions
      security:
        -
          OAuth2:
            - ViewCompetitions
      operationId: getCompetitionsToClone
      summary: Get Competition To Clone
      description: Clones a Competition for the identifier provided
  /member-token:
    description: >-
      The services returns a JWT token used to authorize requests to the other service end points. Use
      this JWT as an auth header parameter for future requests: 
      
      --header 'Authorization: Bearer <jwt-token-from-api>'
    post:
      tags:
        - member-token
      security:
        -
          OAuth2: []
      operationId: createMemberToken
      description: Get Jwt Token
  /entity-changes:
    post:
      tags:
        - entity-changes
      operationId: manageEntityChangeSubscription
      description: subscribes a client to receive out-of-band data
    delete:
      operationId: unsubscribeFromEntityChanges
  /connections/delete:
    post:
      tags:
        - connections
      security:
        -
          OAuth2:
            - AdminConsumer
      operationId: deleteConnectionsByQuery
      description: >-
        Delete a RabbitMQ Connection or a list of RabbitMQ Connections from Ziqni by unique Connection
        ID's or any other POST body parameters using the POST method
  /connections/query:
    post:
      tags:
        - connections
      security:
        -
          OAuth2:
            - AdminConsumer
      operationId: getConnectionsByQuery
      description: >-
        Retrieve a RabbitMQ Connection or a list of RabbitMQ Connections from Ziqni by unique
        Connection ID's or any other Post body parameters using the POST method
  /members:
    summary: Manage members
    description: These operations allow you to manage members in your project.
    get:
      tags:
        - members
      security:
        -
          OAuth2:
            - ViewMembers
      operationId: getMembers
      summary: Get members
      description: >-
        Returns a list of Members. This assumes that members have first been uploaded via a POST
        request or web console
      x-vue-item: Member
      x-vue-list: Members
    put:
      tags:
        - members
      security:
        -
          OAuth2:
            - ManageMembers
      operationId: updateMembers
      summary: Update members
      description: Update existing Members in the Ziqni database
    post:
      tags:
        - members
      security:
        -
          OAuth2:
            - ManageMembers
      operationId: createMembers
      summary: Create members
      description: Create new Members in the Ziqni database
    delete:
      tags:
        - members
      security:
        -
          OAuth2:
            - AdminMembers
      operationId: deleteMembers
      summary: Delete members
      description: Delete Members for a given identifier specified
  /connections/_describe:
    get:
      tags:
        - connections
      security:
        -
          OAuth2:
            - AdminConsumer
      operationId: describeConnectionObject
      description: Get all the parameter for the connection based on the connection type
  /connections:
    get:
      tags:
        - connections
      security:
        -
          OAuth2:
            - AdminConsumer
      operationId: getConnections
      description: Return a list of Consumer Connections
    put:
      tags:
        - connections
      security:
        -
          OAuth2:
            - AdminConsumer
      operationId: updateConnections
      description: Update an existing Consumer Connection in the Ziqni system
    post:
      tags:
        - connections
      security:
        -
          OAuth2:
            - AdminConsumer
      operationId: createConnections
      description: Create a new Consumer Connection in the Ziqni system
    delete:
      tags:
        - connections
      security:
        -
          OAuth2:
            - AdminConsumer
      operationId: deleteConnections
      description: Delete the Consumer Connection for a given identifier specified
  '/competitions/{id}/leaderboard':
    get:
      tags:
        - competitions
      deprecated: true
      security:
        -
          OAuth2:
            - ViewCompetitions
      operationId: getLeaderboardByCompetitionId
      description: Use /leadeboard instead. Returns a list of Leaderborads for the Competition id provided
  /leaderboard:
    get:
      tags:
        - leaderboard
      deprecated: false
      security:
        -
          OAuth2:
            - ViewCompetitions
      operationId: getLeaderboardById
      description: Returns a leaderborads for the competition or contest id provided
  /log-events/query:
    post:
      tags:
        - logEvents
      security:
        -
          OAuth2:
            - ViewLogEvents
      operationId: getLogEventsByQuery
      description: >-
        Retrieve Log Events from Ziqni database by unique Log Events ID's or any other POST body
        parameters using the POST method
  /entrants:
    post:
      tags:
        - entrants
      deprecated: false
      security:
        -
          OAuth2:
            - ManageCompetition
      operationId: updateEntrants
      description: Updates the status of the Entrants for a Competition id provided
  /entrants/query:
    summary: Get entrants by query
    description: This operation allows you to get entrants in your project using a query.
    post:
      tags:
        - entrants
      security:
        -
          OAuth2:
            - ViewCompetitions
      operationId: getEntrantsByQuery
      summary: Get entrants by query
      description: >-
        Retrieve ConteEntrants from Ziqni database by unique Contests ID's or any other POST body
        parameters using the POST method
  /graphs:
    summary: Structures the connections data as a graph.
    description: >-
      The ZIQNI graph data structure consists of a finite (and possibly mutable) set of vertices (also
      called nodes or points), together with a set of ordered pairs for a directed graph. These pairs
      are known as edges (also called links or lines), and for a directed graph are also known as edges
      but also sometimes arrows or arcs whicj are joined using the dependant on must or should within
      achievements.
    post:
      tags:
        - graphs
      security:
        -
          OAuth2:
            - ViewMissions
      operationId: getGraph
      summary: Get achievements by member reference id
      description: Returns a list of graphs based on the entity type.
  /entrants/export:
    summary: Get entrants by query
    description: This operation allows you to get entrants in your project using a query.
    post:
      tags:
        - entrants
      security:
        -
          OAuth2:
            - ViewCompetitions
      operationId: exportEntrantsByQuery
      summary: Get entrants by query
      description: >-
        Retrieve ConteEntrants from Ziqni database by unique Contests ID's or any other POST body
        parameters using the POST method
  /instant-wins/delete:
    summary: Delete instant wins by query
    description: This operation allows you to delete instant wins in your project using a query.
    post:
      tags:
        - instant-wins
      security:
        -
          OAuth2:
            - AdminInstantWins
      operationId: deleteInstantWinsByQuery
      summary: Delete instant-wins by query
      description: >-
        Delete Instant wins from Ziqni database by unique Instant win ID's or any other POST body
        parameters using the POST method
  /instant-wins/query:
    summary: Get instant wins by query
    description: This operation allows you to get instant wins in your project using a query.
    post:
      tags:
        - instant-wins
      security:
        -
          OAuth2:
            - ViewInstantWins
      operationId: getInstantWinsByQuery
      summary: Get instant wins by query
      description: >-
        Retrieve Instant wins from Ziqni database by unique Instant win ID's or any other POST body
        parameters using the POST method
  /instant-wins:
    summary: Manage instant wins
    description: These operations allow you to manage instant wins in your project.
    get:
      tags:
        - instant-wins
      security:
        -
          OAuth2:
            - ViewInstantWins
      operationId: getInstantWins
      summary: Get instant wins
      description: >-
        Returns a list of Instant wins. This assumes that instant wins have first been uploaded via a
        POST request or web console
      x-vue-item: InstantWin
      x-vue-list: InstantWins
    put:
      tags:
        - instant-wins
      security:
        -
          OAuth2:
            - ManageInstantWins
      operationId: updateInstantWins
      summary: Update instant wins
      description: Update existing Instant wins in the Ziqni database
    post:
      tags:
        - instant-wins
      security:
        -
          OAuth2:
            - AdminInstantWins
      operationId: createInstantWins
      summary: Create instant wins
      description: Create new Instant win in the Ziqni database
    delete:
      tags:
        - instant-wins
      security:
        -
          OAuth2:
            - AdminInstantWins
      operationId: deleteInstantWins
      summary: Delete instant wins
      description: Delete Instant win for a given identifier specified
  /awards:
    get:
      tags:
        - awards
      security:
        -
          OAuth2:
            - ViewAwards
      operationId: getAwards
      description: Returns a list of Awards.
      x-vue-item: Award
      x-vue-list: Awards
    put:
      tags:
        - api-keys
      security:
        -
          OAuth2:
            - AdminApi
      operationId: updateAwards
      summary: Update awards
      description: Update an existing award in the Ziqni system
components:
  securitySchemes:
    OAuth2:
      flows:
        authorizationCode:
          authorizationUrl: 'https://identity.ziqni.com/realms/ziqni/protocol/openid-connect/auth'
          tokenUrl: 'https://identity.ziqni.com/realms/ziqni/protocol/openid-connect/token'
          scopes:
            AdminAchievements: Grants full read and write access
            ManageAchievements: Grants read and restricted write access
            ViewAchievement: Grants read access
            AdminActions: Grants full read and write access
            ViewActions: Grants read access
            AdminApi: Grants full read and write access
            AdminClaim: Grants full read and write access
            ViewAwards: Grants read access
            AdminCollaborator: Grants full read and write access
            AdminCompetition: Grants full read and write access
            ManageCompetition: Grants read and restricted write access
            ViewCompetitions: Grants read access
            AdminConsumer: Grants full read and write access
            AdminContest: Grants full read and write access
            ManageContest: Grants read and restricted write access
            ViewContest: Grants read access
            AdminCustomFields: Grants full read and write access
            ViewCustomFields: Grants read access
            AdminEvents: Grants full read and write access
            ViewEvents: Grants read access
            AdminObjects: Grants full read and write access
            ManageObjects: Grants read and restricted write access
            ViewObjects: Grants read access
            AdminLanguage: Grants full read and write access
            ViewLanguage: Grants read access
            logout: Grants read access
            AdminMembers: Grants full read and write access
            ManageMembers: Grants read and restricted write access
            ViewMembers: Grants read access
            AdminMessages: Grants full read and write access
            ManageMessages: Grants read and restricted write access
            ViewMessages: Grants read access
            AdminProducts: Grants full read and write access
            ManageProducts: Grants read and restricted write access
            ViewProducts: Grants read access
            ManageFileObjectRep: Grants read and restricted write access
            AdminRewards: Grants full read and write access
            ManageRewards: Grants read and restricted write access
            ViewRewards: Grants read access
            AdminRewardType: Grants full read and write access
            ManageRewardType: Grants read and restricted write access
            ViewRewardType: Grants read access
            ViewRules: Grants read access
            AdminSpaces: Grants full read and write access
            ViewSpaces: Grants read access
            AdminTransformers: Grants full read and write access
            ViewAccountSettings: Grants read access
            AdminUOM: Grants full read and write access
            ManageUOM: Grants read and restricted write access
            ViewUOM: Grants read access
            AdminUser: Grants full read and write access
            ViewUser: Grants read access
            AdminWebhooks: Grants full read and write access
            AdminTags: Grants full read and write access
            ManageTags: Grants read and restricted write access
            ViewTags: Grants read access
            Owner: The space owner
            Collaborator: A collaborator in this space
      type: oauth2
security:
  -
    OAuth2:
      - Owner
      - Collaborator
tags:
  -
    name: products
    description: Perform REST operations on Products
  -
    name: members
    description: Perform REST operations on Members
  -
    name: competitions
    description: Perform REST operations on Competitions
  -
    name: contests
    description: Perform REST operations on Contests
  -
    name: achievements
    description: Perform REST operations on Achievements
  -
    name: rewards
    description: Perform REST operations on Rewards
  -
    name: awards
    description: Perform REST operations on Awards
  -
    name: reward-types
    description: Perform REST operations on Reward Types
  -
    name: action-types
    description: Perform REST operations on Action Types
  -
    name: rules
    description: Perform REST operations on Rules
  -
    name: languages
    description: Perform REST operations on Languages
  -
    name: custom-fields
    description: Perform REST operations on Custom Fields
  -
    name: units-of-measure
    description: Perform REST operations on Units Of Measure
  -
    name: transformers
    description: Perform REST operations on transformers
  -
    name: consumers
    description: Perform REST operations on consumers
  -
    name: webhooks
    description: Perform REST operations on webhooks
  -
    name: events
    description: Perform REST operations on events
  -
    name: spaces
    description: Perform REST operations on users spaces
  -
    name: users
    description: Perform REST operations on users managed by this space
  -
    name: user
    description: Perform REST operations for the current user
  -
    name: two-factor-auth
    description: Perform REST operations for the current users two factor settings
  -
    name: collaborators
    description: Perform REST operations on collaborators
  -
    name: api-keys
    description: Perform REST operations on api keys
  -
    name: repositories
    description: Perform REST operations on repositories
  -
    name: file-objects
    description: Perform REST operations on file-objects
  -
    name: tags
    description: Perform REST operations on tags
  -
    name: translations
    description: Perform REST operations on translations
  -
    name: account-messages
    description: Perform operations on Account Messages.
  -
    name: member-messages
    description: Perform operations on Member Messages
  -
    name: notifications
    description: Perform operations on Notifications
  -
    name: compute-engine
    description: Perform operations on Compute Engine