apiName: ZiqniAdminSDK
packageName: Ziqni
disallowAdditionalPropertiesIfNotPresent: false
hideGenerationTimestamp: true
netCoreProjectFile: false
targetFramework: net6.0
frameworkStrategy: net6.0
nullableReferenceTypes: true
description: