//
// AchievementIssuedCount.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AchievementIssuedCount: Codable, Hashable {

    /** A unique identifier of a Entity */
    public var entityId: String
    /** The value in how many times the achievemnt was issued */
    public var countValue: Int

    public init(entityId: String, countValue: Int) {
        self.entityId = entityId
        self.countValue = countValue
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case entityId
        case countValue
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(entityId, forKey: .entityId)
        try container.encode(countValue, forKey: .countValue)
    }
}

