//
// AchievementLiveStatusRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AchievementLiveStatusRequest: Codable, Hashable {

    /** A unique system generated identifier */
    public var id: String
    public var status: AchievementLiveStatus

    public init(id: String, status: AchievementLiveStatus) {
        self.id = id
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(status, forKey: .status)
    }
}

