//
// CreateActionTypeRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateActionTypeRequest: Codable, Hashable {

    /** A list of custom field entries */
    public var customFields: [String: AnyCodable]?
    /** A list of id's used to tag models */
    public var tags: [String]?
    public var metadata: [String: String]?
    /** The name of the Action Helper */
    public var name: String
    /** A unique key that represents an action helper */
    public var key: String
    /** The description of the rule action helper for your reference */
    public var description: String?
    /** Additional constraints */
    public var addConstraints: [String]?
    /** The unit of measure id */
    public var unitOfMeasure: String

    public init(customFields: [String: AnyCodable]? = nil, tags: [String]? = nil, metadata: [String: String]? = nil, name: String, key: String, description: String? = nil, addConstraints: [String]? = nil, unitOfMeasure: String) {
        self.customFields = customFields
        self.tags = tags
        self.metadata = metadata
        self.name = name
        self.key = key
        self.description = description
        self.addConstraints = addConstraints
        self.unitOfMeasure = unitOfMeasure
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case customFields
        case tags
        case metadata
        case name
        case key
        case description
        case addConstraints
        case unitOfMeasure
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(customFields, forKey: .customFields)
        try container.encodeIfPresent(tags, forKey: .tags)
        try container.encodeIfPresent(metadata, forKey: .metadata)
        try container.encode(name, forKey: .name)
        try container.encode(key, forKey: .key)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(addConstraints, forKey: .addConstraints)
        try container.encode(unitOfMeasure, forKey: .unitOfMeasure)
    }
}

