//
// UpdateTagRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Request for tag update */
public struct UpdateTagRequest: Codable, Hashable {

    /** A unique system generated identifier */
    public var id: String
    /** The name of the tag */
    public var name: String?
    /** The description of the tag for your reference */
    public var description: String?
    /** The model name the tag refers to */
    public var entityTypes: [String]?
    public var metadata: [String: String]?

    public init(id: String, name: String? = nil, description: String? = nil, entityTypes: [String]? = nil, metadata: [String: String]? = nil) {
        self.id = id
        self.name = name
        self.description = description
        self.entityTypes = entityTypes
        self.metadata = metadata
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case description
        case entityTypes
        case metadata
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(entityTypes, forKey: .entityTypes)
        try container.encodeIfPresent(metadata, forKey: .metadata)
    }
}

