/*
 * ZIQNI Admin API
 *
 * Ziqni Application Services are used to manage and configure spaces.
 *
 * The version of the OpenAPI document: 3.0.1
 * Contact: support@ziqni.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// CreateAchievementRequestAllOf
    /// </summary>
    [DataContract]
    public partial class CreateAchievementRequestAllOf :  IEquatable<CreateAchievementRequestAllOf>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateAchievementRequestAllOf" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateAchievementRequestAllOf() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateAchievementRequestAllOf" /> class.
        /// </summary>
        /// <param name="name">A name for the Achievement. Can be translated (required).</param>
        /// <param name="description">A name for the Achievement. Can be translated.</param>
        /// <param name="termsAndConditions">Terms and conditions of an achievement. Can be translated.</param>
        /// <param name="icon">An Icon id that has been pre uploaded to the system to display for Achievement.</param>
        /// <param name="rules">rules.</param>
        /// <param name="scheduling">scheduling (required).</param>
        /// <param name="maxNumberOfIssues">Maximum number of issued achievements.</param>
        /// <param name="translations">translations.</param>
        /// <param name="rewards">rewards.</param>
        /// <param name="constraints">Additional constraints (required).</param>
        /// <param name="achievementDependencies">achievementDependencies.</param>
        /// <param name="memberTagsFilter">memberTagsFilter.</param>
        /// <param name="productTagsFilter">productTagsFilter.</param>
        /// <param name="addConstraints">addConstraints.</param>
        public CreateAchievementRequestAllOf(string name = default(string), string description = default(string), string termsAndConditions = default(string), string icon = default(string), List<Rule> rules = default(List<Rule>), Scheduling scheduling = default(Scheduling), int maxNumberOfIssues = default(int), List<Translation> translations = default(List<Translation>), List<CreateRewardRequest> rewards = default(List<CreateRewardRequest>), List<string> constraints = default(List<string>), DependantOn achievementDependencies = default(DependantOn), DependantOn memberTagsFilter = default(DependantOn), DependantOn productTagsFilter = default(DependantOn), List<string> addConstraints = default(List<string>))
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new InvalidDataException("name is a required property for CreateAchievementRequestAllOf and cannot be null");
            }
            else
            {
                this.Name = name;
            }

            // to ensure "scheduling" is required (not null)
            if (scheduling == null)
            {
                throw new InvalidDataException("scheduling is a required property for CreateAchievementRequestAllOf and cannot be null");
            }
            else
            {
                this.Scheduling = scheduling;
            }

            // to ensure "constraints" is required (not null)
            if (constraints == null)
            {
                throw new InvalidDataException("constraints is a required property for CreateAchievementRequestAllOf and cannot be null");
            }
            else
            {
                this.Constraints = constraints;
            }

            this.Description = description;
            this.TermsAndConditions = termsAndConditions;
            this.Icon = icon;
            this.Rules = rules;
            this.MaxNumberOfIssues = maxNumberOfIssues;
            this.Translations = translations;
            this.Rewards = rewards;
            this.AchievementDependencies = achievementDependencies;
            this.MemberTagsFilter = memberTagsFilter;
            this.ProductTagsFilter = productTagsFilter;
            this.AddConstraints = addConstraints;
        }

        /// <summary>
        /// A name for the Achievement. Can be translated
        /// </summary>
        /// <value>A name for the Achievement. Can be translated</value>
        [DataMember(Name="name", EmitDefaultValue=true)]
        public string Name { get; set; }

        /// <summary>
        /// A name for the Achievement. Can be translated
        /// </summary>
        /// <value>A name for the Achievement. Can be translated</value>
        [DataMember(Name="description", EmitDefaultValue=false)]
        public string Description { get; set; }

        /// <summary>
        /// Terms and conditions of an achievement. Can be translated
        /// </summary>
        /// <value>Terms and conditions of an achievement. Can be translated</value>
        [DataMember(Name="termsAndConditions", EmitDefaultValue=false)]
        public string TermsAndConditions { get; set; }

        /// <summary>
        /// An Icon id that has been pre uploaded to the system to display for Achievement
        /// </summary>
        /// <value>An Icon id that has been pre uploaded to the system to display for Achievement</value>
        [DataMember(Name="icon", EmitDefaultValue=false)]
        public string Icon { get; set; }

        /// <summary>
        /// Gets or Sets Rules
        /// </summary>
        [DataMember(Name="rules", EmitDefaultValue=false)]
        public List<Rule> Rules { get; set; }

        /// <summary>
        /// Gets or Sets Scheduling
        /// </summary>
        [DataMember(Name="scheduling", EmitDefaultValue=true)]
        public Scheduling Scheduling { get; set; }

        /// <summary>
        /// Maximum number of issued achievements
        /// </summary>
        /// <value>Maximum number of issued achievements</value>
        [DataMember(Name="maxNumberOfIssues", EmitDefaultValue=false)]
        public int MaxNumberOfIssues { get; set; }

        /// <summary>
        /// Gets or Sets Translations
        /// </summary>
        [DataMember(Name="translations", EmitDefaultValue=false)]
        public List<Translation> Translations { get; set; }

        /// <summary>
        /// Gets or Sets Rewards
        /// </summary>
        [DataMember(Name="rewards", EmitDefaultValue=false)]
        public List<CreateRewardRequest> Rewards { get; set; }

        /// <summary>
        /// Additional constraints
        /// </summary>
        /// <value>Additional constraints</value>
        [DataMember(Name="constraints", EmitDefaultValue=true)]
        [Obsolete]
        public List<string> Constraints { get; set; }

        /// <summary>
        /// Gets or Sets AchievementDependencies
        /// </summary>
        [DataMember(Name="achievementDependencies", EmitDefaultValue=false)]
        public DependantOn AchievementDependencies { get; set; }

        /// <summary>
        /// Gets or Sets MemberTagsFilter
        /// </summary>
        [DataMember(Name="memberTagsFilter", EmitDefaultValue=false)]
        public DependantOn MemberTagsFilter { get; set; }

        /// <summary>
        /// Gets or Sets ProductTagsFilter
        /// </summary>
        [DataMember(Name="productTagsFilter", EmitDefaultValue=false)]
        public DependantOn ProductTagsFilter { get; set; }

        /// <summary>
        /// Gets or Sets AddConstraints
        /// </summary>
        [DataMember(Name="addConstraints", EmitDefaultValue=false)]
        public List<string> AddConstraints { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CreateAchievementRequestAllOf {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  TermsAndConditions: ").Append(TermsAndConditions).Append("\n");
            sb.Append("  Icon: ").Append(Icon).Append("\n");
            sb.Append("  Rules: ").Append(Rules).Append("\n");
            sb.Append("  Scheduling: ").Append(Scheduling).Append("\n");
            sb.Append("  MaxNumberOfIssues: ").Append(MaxNumberOfIssues).Append("\n");
            sb.Append("  Translations: ").Append(Translations).Append("\n");
            sb.Append("  Rewards: ").Append(Rewards).Append("\n");
            sb.Append("  Constraints: ").Append(Constraints).Append("\n");
            sb.Append("  AchievementDependencies: ").Append(AchievementDependencies).Append("\n");
            sb.Append("  MemberTagsFilter: ").Append(MemberTagsFilter).Append("\n");
            sb.Append("  ProductTagsFilter: ").Append(ProductTagsFilter).Append("\n");
            sb.Append("  AddConstraints: ").Append(AddConstraints).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CreateAchievementRequestAllOf);
        }

        /// <summary>
        /// Returns true if CreateAchievementRequestAllOf instances are equal
        /// </summary>
        /// <param name="input">Instance of CreateAchievementRequestAllOf to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateAchievementRequestAllOf input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                ) && 
                (
                    this.TermsAndConditions == input.TermsAndConditions ||
                    (this.TermsAndConditions != null &&
                    this.TermsAndConditions.Equals(input.TermsAndConditions))
                ) && 
                (
                    this.Icon == input.Icon ||
                    (this.Icon != null &&
                    this.Icon.Equals(input.Icon))
                ) && 
                (
                    this.Rules == input.Rules ||
                    this.Rules != null &&
                    input.Rules != null &&
                    this.Rules.SequenceEqual(input.Rules)
                ) && 
                (
                    this.Scheduling == input.Scheduling ||
                    (this.Scheduling != null &&
                    this.Scheduling.Equals(input.Scheduling))
                ) && 
                (
                    this.MaxNumberOfIssues == input.MaxNumberOfIssues ||
                    (this.MaxNumberOfIssues != null &&
                    this.MaxNumberOfIssues.Equals(input.MaxNumberOfIssues))
                ) && 
                (
                    this.Translations == input.Translations ||
                    this.Translations != null &&
                    input.Translations != null &&
                    this.Translations.SequenceEqual(input.Translations)
                ) && 
                (
                    this.Rewards == input.Rewards ||
                    this.Rewards != null &&
                    input.Rewards != null &&
                    this.Rewards.SequenceEqual(input.Rewards)
                ) && 
                (
                    this.Constraints == input.Constraints ||
                    this.Constraints != null &&
                    input.Constraints != null &&
                    this.Constraints.SequenceEqual(input.Constraints)
                ) && 
                (
                    this.AchievementDependencies == input.AchievementDependencies ||
                    (this.AchievementDependencies != null &&
                    this.AchievementDependencies.Equals(input.AchievementDependencies))
                ) && 
                (
                    this.MemberTagsFilter == input.MemberTagsFilter ||
                    (this.MemberTagsFilter != null &&
                    this.MemberTagsFilter.Equals(input.MemberTagsFilter))
                ) && 
                (
                    this.ProductTagsFilter == input.ProductTagsFilter ||
                    (this.ProductTagsFilter != null &&
                    this.ProductTagsFilter.Equals(input.ProductTagsFilter))
                ) && 
                (
                    this.AddConstraints == input.AddConstraints ||
                    this.AddConstraints != null &&
                    input.AddConstraints != null &&
                    this.AddConstraints.SequenceEqual(input.AddConstraints)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.Description != null)
                    hashCode = hashCode * 59 + this.Description.GetHashCode();
                if (this.TermsAndConditions != null)
                    hashCode = hashCode * 59 + this.TermsAndConditions.GetHashCode();
                if (this.Icon != null)
                    hashCode = hashCode * 59 + this.Icon.GetHashCode();
                if (this.Rules != null)
                    hashCode = hashCode * 59 + this.Rules.GetHashCode();
                if (this.Scheduling != null)
                    hashCode = hashCode * 59 + this.Scheduling.GetHashCode();
                if (this.MaxNumberOfIssues != null)
                    hashCode = hashCode * 59 + this.MaxNumberOfIssues.GetHashCode();
                if (this.Translations != null)
                    hashCode = hashCode * 59 + this.Translations.GetHashCode();
                if (this.Rewards != null)
                    hashCode = hashCode * 59 + this.Rewards.GetHashCode();
                if (this.Constraints != null)
                    hashCode = hashCode * 59 + this.Constraints.GetHashCode();
                if (this.AchievementDependencies != null)
                    hashCode = hashCode * 59 + this.AchievementDependencies.GetHashCode();
                if (this.MemberTagsFilter != null)
                    hashCode = hashCode * 59 + this.MemberTagsFilter.GetHashCode();
                if (this.ProductTagsFilter != null)
                    hashCode = hashCode * 59 + this.ProductTagsFilter.GetHashCode();
                if (this.AddConstraints != null)
                    hashCode = hashCode * 59 + this.AddConstraints.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
