/*
 * ZIQNI Admin API
 *
 * Ziqni Application Services are used to manage and configure spaces.
 *
 * The version of the OpenAPI document: 3.0.1
 * Contact: support@ziqni.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing CreateContestRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateContestRequestTests
    {
        // TODO uncomment below to declare an instance variable for CreateContestRequest
        //private CreateContestRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CreateContestRequest
            //instance = new CreateContestRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CreateContestRequest
        /// </summary>
        [Test]
        public void CreateContestRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" CreateContestRequest
            //Assert.IsInstanceOf(typeof(CreateContestRequest), instance);
        }


        /// <summary>
        /// Test the property 'CustomFields'
        /// </summary>
        [Test]
        public void CustomFieldsTest()
        {
            // TODO unit test for the property 'CustomFields'
        }
        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Test]
        public void TagsTest()
        {
            // TODO unit test for the property 'Tags'
        }
        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Test]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }
        /// <summary>
        /// Test the property 'Row'
        /// </summary>
        [Test]
        public void RowTest()
        {
            // TODO unit test for the property 'Row'
        }
        /// <summary>
        /// Test the property 'Round'
        /// </summary>
        [Test]
        public void RoundTest()
        {
            // TODO unit test for the property 'Round'
        }
        /// <summary>
        /// Test the property 'GroupStage'
        /// </summary>
        [Test]
        public void GroupStageTest()
        {
            // TODO unit test for the property 'GroupStage'
        }
        /// <summary>
        /// Test the property 'GroupStageLabel'
        /// </summary>
        [Test]
        public void GroupStageLabelTest()
        {
            // TODO unit test for the property 'GroupStageLabel'
        }
        /// <summary>
        /// Test the property 'EntrantsFromContest'
        /// </summary>
        [Test]
        public void EntrantsFromContestTest()
        {
            // TODO unit test for the property 'EntrantsFromContest'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'TermsAndConditions'
        /// </summary>
        [Test]
        public void TermsAndConditionsTest()
        {
            // TODO unit test for the property 'TermsAndConditions'
        }
        /// <summary>
        /// Test the property 'RoundType'
        /// </summary>
        [Test]
        public void RoundTypeTest()
        {
            // TODO unit test for the property 'RoundType'
        }
        /// <summary>
        /// Test the property 'MaxNumberOfEntrants'
        /// </summary>
        [Test]
        public void MaxNumberOfEntrantsTest()
        {
            // TODO unit test for the property 'MaxNumberOfEntrants'
        }
        /// <summary>
        /// Test the property 'MinNumberOfEntrants'
        /// </summary>
        [Test]
        public void MinNumberOfEntrantsTest()
        {
            // TODO unit test for the property 'MinNumberOfEntrants'
        }
        /// <summary>
        /// Test the property 'Rules'
        /// </summary>
        [Test]
        public void RulesTest()
        {
            // TODO unit test for the property 'Rules'
        }
        /// <summary>
        /// Test the property 'ScheduledStartDate'
        /// </summary>
        [Test]
        public void ScheduledStartDateTest()
        {
            // TODO unit test for the property 'ScheduledStartDate'
        }
        /// <summary>
        /// Test the property 'ScheduledEndDate'
        /// </summary>
        [Test]
        public void ScheduledEndDateTest()
        {
            // TODO unit test for the property 'ScheduledEndDate'
        }
        /// <summary>
        /// Test the property 'Strategies'
        /// </summary>
        [Test]
        public void StrategiesTest()
        {
            // TODO unit test for the property 'Strategies'
        }
        /// <summary>
        /// Test the property 'Constraints'
        /// </summary>
        [Test]
        public void ConstraintsTest()
        {
            // TODO unit test for the property 'Constraints'
        }
        /// <summary>
        /// Test the property 'AddConstraints'
        /// </summary>
        [Test]
        public void AddConstraintsTest()
        {
            // TODO unit test for the property 'AddConstraints'
        }
        /// <summary>
        /// Test the property 'Translations'
        /// </summary>
        [Test]
        public void TranslationsTest()
        {
            // TODO unit test for the property 'Translations'
        }
        /// <summary>
        /// Test the property 'Rewards'
        /// </summary>
        [Test]
        public void RewardsTest()
        {
            // TODO unit test for the property 'Rewards'
        }

    }

}
