/*
 * ZIQNI Admin API
 *
 * Ziqni Application Services are used to manage and configure spaces.
 *
 * The version of the OpenAPI document: 3.0.1
 * Contact: support@ziqni.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing MemberAwardAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MemberAwardAllOfTests
    {
        // TODO uncomment below to declare an instance variable for MemberAwardAllOf
        //private MemberAwardAllOf instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MemberAwardAllOf
            //instance = new MemberAwardAllOf();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MemberAwardAllOf
        /// </summary>
        [Test]
        public void MemberAwardAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" MemberAwardAllOf
            //Assert.IsInstanceOf(typeof(MemberAwardAllOf), instance);
        }


        /// <summary>
        /// Test the property 'RewardId'
        /// </summary>
        [Test]
        public void RewardIdTest()
        {
            // TODO unit test for the property 'RewardId'
        }
        /// <summary>
        /// Test the property 'RewardType'
        /// </summary>
        [Test]
        public void RewardTypeTest()
        {
            // TODO unit test for the property 'RewardType'
        }
        /// <summary>
        /// Test the property 'RewardTypeId'
        /// </summary>
        [Test]
        public void RewardTypeIdTest()
        {
            // TODO unit test for the property 'RewardTypeId'
        }
        /// <summary>
        /// Test the property 'RewardValue'
        /// </summary>
        [Test]
        public void RewardValueTest()
        {
            // TODO unit test for the property 'RewardValue'
        }
        /// <summary>
        /// Test the property 'Delay'
        /// </summary>
        [Test]
        public void DelayTest()
        {
            // TODO unit test for the property 'Delay'
        }
        /// <summary>
        /// Test the property 'EntityType'
        /// </summary>
        [Test]
        public void EntityTypeTest()
        {
            // TODO unit test for the property 'EntityType'
        }
        /// <summary>
        /// Test the property 'EntityId'
        /// </summary>
        [Test]
        public void EntityIdTest()
        {
            // TODO unit test for the property 'EntityId'
        }
        /// <summary>
        /// Test the property 'PointInTime'
        /// </summary>
        [Test]
        public void PointInTimeTest()
        {
            // TODO unit test for the property 'PointInTime'
        }
        /// <summary>
        /// Test the property 'Period'
        /// </summary>
        [Test]
        public void PeriodTest()
        {
            // TODO unit test for the property 'Period'
        }
        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Test]
        public void TagsTest()
        {
            // TODO unit test for the property 'Tags'
        }
        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Test]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }
        /// <summary>
        /// Test the property 'Constraints'
        /// </summary>
        [Test]
        public void ConstraintsTest()
        {
            // TODO unit test for the property 'Constraints'
        }
        /// <summary>
        /// Test the property 'ClaimedTimestamp'
        /// </summary>
        [Test]
        public void ClaimedTimestampTest()
        {
            // TODO unit test for the property 'ClaimedTimestamp'
        }

    }

}
