/*
 * ZIQNI Admin API
 *
 * Ziqni Application Services are used to manage and configure spaces.
 *
 * The version of the OpenAPI document: 3.0.1
 * Contact: support@ziqni.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing RuleOperandLookupRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RuleOperandLookupRequestTests
    {
        // TODO uncomment below to declare an instance variable for RuleOperandLookupRequest
        //private RuleOperandLookupRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RuleOperandLookupRequest
            //instance = new RuleOperandLookupRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RuleOperandLookupRequest
        /// </summary>
        [Test]
        public void RuleOperandLookupRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" RuleOperandLookupRequest
            //Assert.IsInstanceOf(typeof(RuleOperandLookupRequest), instance);
        }


        /// <summary>
        /// Test the property 'Context'
        /// </summary>
        [Test]
        public void ContextTest()
        {
            // TODO unit test for the property 'Context'
        }
        /// <summary>
        /// Test the property 'SearchText'
        /// </summary>
        [Test]
        public void SearchTextTest()
        {
            // TODO unit test for the property 'SearchText'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Skip'
        /// </summary>
        [Test]
        public void SkipTest()
        {
            // TODO unit test for the property 'Skip'
        }
        /// <summary>
        /// Test the property 'Limit'
        /// </summary>
        [Test]
        public void LimitTest()
        {
            // TODO unit test for the property 'Limit'
        }
        /// <summary>
        /// Test the property 'Constraints'
        /// </summary>
        [Test]
        public void ConstraintsTest()
        {
            // TODO unit test for the property 'Constraints'
        }
        /// <summary>
        /// Test the property 'Operand'
        /// </summary>
        [Test]
        public void OperandTest()
        {
            // TODO unit test for the property 'Operand'
        }

    }

}
