/*
 * ZIQNI Admin API
 *
 * Ziqni Application Services are used to manage and configure spaces.
 *
 * The version of the OpenAPI document: 3.0.1
 * Contact: support@ziqni.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Ziqni
{
    /// <summary>
    /// QuerySingle
    /// </summary>
    [DataContract]
    public partial class QuerySingle :  IEquatable<QuerySingle>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="QuerySingle" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected QuerySingle() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="QuerySingle" /> class.
        /// </summary>
        /// <param name="queryField">The key of the parameter that is being searched (required).</param>
        /// <param name="queryValue">The value of the parameter that is being searched (required).</param>
        public QuerySingle(string queryField = default(string), string queryValue = default(string))
        {
            // to ensure "queryField" is required (not null)
            if (queryField == null)
            {
                throw new InvalidDataException("queryField is a required property for QuerySingle and cannot be null");
            }
            else
            {
                this.QueryField = queryField;
            }

            // to ensure "queryValue" is required (not null)
            if (queryValue == null)
            {
                throw new InvalidDataException("queryValue is a required property for QuerySingle and cannot be null");
            }
            else
            {
                this.QueryValue = queryValue;
            }

        }

        /// <summary>
        /// The key of the parameter that is being searched
        /// </summary>
        /// <value>The key of the parameter that is being searched</value>
        [DataMember(Name="queryField", EmitDefaultValue=true)]
        public string QueryField { get; set; }

        /// <summary>
        /// The value of the parameter that is being searched
        /// </summary>
        /// <value>The value of the parameter that is being searched</value>
        [DataMember(Name="queryValue", EmitDefaultValue=true)]
        public string QueryValue { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class QuerySingle {\n");
            sb.Append("  QueryField: ").Append(QueryField).Append("\n");
            sb.Append("  QueryValue: ").Append(QueryValue).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as QuerySingle);
        }

        /// <summary>
        /// Returns true if QuerySingle instances are equal
        /// </summary>
        /// <param name="input">Instance of QuerySingle to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(QuerySingle input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.QueryField == input.QueryField ||
                    (this.QueryField != null &&
                    this.QueryField.Equals(input.QueryField))
                ) && 
                (
                    this.QueryValue == input.QueryValue ||
                    (this.QueryValue != null &&
                    this.QueryValue.Equals(input.QueryValue))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.QueryField != null)
                    hashCode = hashCode * 59 + this.QueryField.GetHashCode();
                if (this.QueryValue != null)
                    hashCode = hashCode * 59 + this.QueryValue.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
